def get_points(amenitie):
    switcher = {
        'First aid kit': 4,
        'Lockbox': 2,
        'Keypad': 2,
        'Smart lock': 4,
        'Sound system': 3,
        'Washer / Dryer': 5,
        'Laptop friendly workspace': 2,
        'Dishwasher': 5,
        'Pets live on this property': 2,
        'Pool': 4,
        'Accessible-height toilet': 3,
        'Kitchen': 5,
        'Fire extinguisher': 2,
        'Heating': 5,
        'Full kitchen': 5,
        'Hair dryer': 3,
        'Heated towel rack': 2,
        'Air conditioning': 4,
        'Children’s books and toys': 1,
        'Baby bath': 2,
        'Wide hallways': 1,
        'Essentials': 5,
        'Wide entrance for guests': 1,
        'toilet': 5,
        'Dog(s)': 1,
        'Cable TV': 4,
        'Wheelchair accessible': 2,
        'Safety card': 2,
        'Suitable for events': 4,
        'High chair': 1,
        'Hot tub': 5,
        'Bidet': 2,
        'Flat path to guest entrance': 1,
        'Outlet covers': 2,
        'Ski-in/Ski-out': 4,
        'Fixed grab bars for shower': 3,
        'Free parking on premises': 5,
        'Espresso machine': 2,
        'Smoking allowed': 1,
        'Stove': 2,
        'Coffee maker': 3,
        'Step-free shower': 2,
        'Baby monitor': 4,
        'Bathtub': 2,
        'Handheld shower head': 1,
        'Fixed grab bars for toilet': 1,
        'Ethernet connection': 4,
        'Smart TV': 4,
        'DVD player': 3,
        'Gym': 4,
        'Buzzer/wireless intercom': 5,
        'Wide entryway': 2,
        'EV charger': 4,
        'Balcony': 4,
        'Fireplace guards': 2,
        'Bedroom comforts': 3,
        'Cooking basics': 5,
        'Private living room': 5,
        'Day bed': 4,
        'Air purifier': 2,
        'TV': 5,
        'Doorman': 2,
        'Oven': 4,
        'Breakfast': 3,
        'Indoor fireplace': 3,
        'Long term stays allowed': 2,
        'Stair gates': 3,
        'Iron': 3,
        'Wide entrance': 2,
        'Garden or backyard': 3,
        'Carbon monoxide detector': 1,
        'Hangers': 1,
        'Building staff': 1,
        'Pets allowed': 2,
        'Firm mattress': 2,
        'Lake access': 3,
        'Free street parking': 4,
        'Other': 0,
        'Cleaning before checkout': 0,
        'Children’s dinnerware': 1,
        'Disabled parking spot': 3,
        'Body soap': 1,
        'Soaking tub': 3,
        'Dishes and silverware': 4,
        'Changing table': 1,
        'Beachfront': 4,
        'Bath towel': 1,
        'Accessible-height bed': 1,
        'No stairs or steps to enter': 0,
        'Crib': 2,
        'Wifi': 5,
        'Paid parking off premises': 4,
        'Hot water kettle': 1,
        'Washer': 4,
        'Window guards': 1,
        'Shower chair': 1,
        'Mountain view': 2,
        'Extra pillows and blankets': 1,
        'BBQ grill': 3,
        'Other pet(s)': 2,
        '24-hour check-in': 3,
        'Pocket wifi': 4,
        'Well-lit path to entrance': 1,
        'Wide clearance to shower': 1,
        'Kitchenette': 4,
        'Extra space around bed': 1,
        'Bed linens': 1,
        'Game console': 3,
        'Host greets you': 4,
        'Sun loungers': 2,
        'Ground floor access': 1,
        'Self check-in': 2,
        'Internet': 5,
        'Beach essentials': 4,
        'Babysitter recommendations': 2,
        'Private bathroom': 5,
        'Paid parking on premises': 1,
        'Family/kid friendly': 2,
        'Toilet paper': 4,
        'Walk-in shower': 2,
        'Dryer': 4,
        'Electric profiling bed': 2,
        'Heated floors': 3,
        'Wine cooler': 1,
        'Cat(s)': 1,
        'Room-darkening shades': 3,
        'Bathtub with bath chair': 1,
        'Elevator': 4,
        'Smoke detector': 1,
        'Hot water': 4,
        'Microwave': 4,
        'Lock on bedroom door': 2,
        'Shampoo': 2,
        'Table corner guards': 1,
        'Luggage dropoff allowed': 3,
        'Waterfront': 2,
        'Single level home': 1,
        'Pack ’n Play/travel crib': 1,
        'Private entrance': 2,
        'Patio or balcony': 3,
        'Wide doorway to guest bathroom': 1,
        'Bathroom essentials': 5,
        'Refrigerator': 4,
    }
    return switcher.get(amenitie, 0)