def get_points(amenitie):
    switcher = {
        'First aid kit': 7,
        'Lockbox': 3,
        'Keypad': 1,
        'Smart lock': 5,
        'Sound system': 8,
        'Washer / Dryer': 5,
        'Laptop friendly workspace': 3,
        'Dishwasher': 7,
        'Pets live on this property': 2,
        'Pool': 10,
        'Accessible-height toilet': 5,
        'Kitchen': 1,
        'Fire extinguisher': 2,
        'Heating': 2,
        'Full kitchen': 4,
        'Hair dryer': 3,
        'Heated towel rack': 2,
        'Air conditioning': 7,
        'Children’s books and toys': 4,
        'Baby bath': 4,
        'Wide hallways': 1,
        'Essentials': 1,
        'Wide entrance for guests': 1,
        'toilet': 1,
        'Dog(s)': 4,
        'Cable TV': 5,
        'Wheelchair accessible': 5,
        'Safety card': 4,
        'Suitable for events': 8,
        'High chair': 4,
        'Hot tub': 10,
        'Bidet': 3,
        'Flat path to guest entrance': 1,
        'Outlet covers': 3,
        'Ski-in/Ski-out': 9,
        'Fixed grab bars for shower': 2,
        'Free parking on premises': 7,
        'Espresso machine': 6,
        'Smoking allowed': 4,
        'Stove': 4,
        'Coffee maker': 6,
        'Step-free shower': 4,
        'Baby monitor': 7,
        'Bathtub': 4,
        'Handheld shower head': 2,
        'Fixed grab bars for toilet': 2,
        'Ethernet connection': 5,
        'Smart TV': 7,
        'DVD player': 7,
        'Gym': 10,
        'Buzzer/wireless intercom': 7,
        'Wide entryway': 2,
        'EV charger': 9,
        'Balcony': 7,
        'Fireplace guards': 4,
        'Bedroom comforts': 5,
        'Cooking basics': 2,
        'Private living room': 4,
        'Day bed': 4,
        'Air purifier': 7,
        'TV': 5,
        'Doorman': 5,
        'Oven': 5,
        'Breakfast': 8,
        'Indoor fireplace': 6,
        'Long term stays allowed': 2,
        'Stair gates': 1,
        'Iron': 3,
        'Wide entrance': 2,
        'Garden or backyard': 6,
        'Carbon monoxide detector': 2,
        'Hangers': 3,
        'Building staff': 4,
        'Pets allowed': 6,
        'Firm mattress': 2,
        'Lake access': 2,
        'Free street parking': 6,
        'Other': 0,
        'Cleaning before checkout': 0,
        'Children’s dinnerware': 3,
        'Disabled parking spot': 6,
        'Body soap': 3,
        'Soaking tub': 7,
        'Dishes and silverware': 4,
        'Changing table': 2,
        'Beachfront': 9,
        'Bath towel': 2,
        'Accessible-height bed': 2,
        'No stairs or steps to enter': 0,
        'Crib': 4,
        'Wifi': 5,
        'Paid parking off premises': 5,
        'Hot water kettle': 2,
        'Washer': 4,
        'Window guards': 2,
        'Shower chair': 1,
        'Mountain view': 8,
        'Extra pillows and blankets': 2,
        'BBQ grill': 5,
        'Other pet(s)': 6,
        '24-hour check-in': 4,
        'Pocket wifi': 7,
        'Well-lit path to entrance': 2,
        'Wide clearance to shower': 3,
        'Kitchenette': 5,
        'Extra space around bed': 2,
        'Bed linens': 2,
        'Game console': 8,
        'Host greets you': 2,
        'Sun loungers': 3,
        'Ground floor access': 3,
        'Self check-in': 2,
        'Internet': 5,
        'Beach essentials': 6,
        'Babysitter recommendations': 5,
        'Private bathroom': 3,
        'Paid parking on premises': 1,
        'Family/kid friendly': 3,
        'Toilet paper': 1,
        'Walk-in shower': 2,
        'Dryer': 3,
        'Electric profiling bed': 7,
        'Heated floors': 9,
        'Wine cooler': 5,
        'Cat(s)': 4,
        'Room-darkening shades': 2,
        'Bathtub with bath chair': 5,
        'Elevator': 2,
        'Smoke detector': 2,
        'Hot water': 2,
        'Microwave': 3,
        'Lock on bedroom door': 1,
        'Shampoo': 1,
        'Table corner guards': 1,
        'Luggage dropoff allowed': 1,
        'Waterfront': 8,
        'Single level home': 4,
        'Pack ’n Play/travel crib': 2,
        'Private entrance': 3,
        'Patio or balcony': 7,
        'Wide doorway to guest bathroom': 1,
        'Bathroom essentials': 3,
        'Refrigerator': 4,
    }
    return switcher.get(amenitie, 0)